version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sensor_data_benchmark
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped