version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sensor_data_benchmark
      GLIBC_TUNABLES: glibc.pthread.rseq=0
    command:
      - mongod
      - --auth
      - --wiredTigerCacheSizeGB
      - "2"
volumes:
  mongo-data:
    driver: local